### ISSUE TITLE
No warning is printed when using bindings without @component

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-decorators#11]
A warning should be printed to the console, otherwise it is not clear why the bindings do not work in this case.

**Comment by tbuschto** [comment]
I can not reproduce this. It prints `Could not resolve one-way binding on CustomComponent: Not appended to a @component` to the console as expected. It can get a bit weird for a component-within-component scenario since the binding is then targeting the wrong widget, but there is no good way to detect this. 

Close issues for now, re-open if you disagree.
